rvm:
  - 2.4.1
services:
  - redis-server
  - postgresql
addons:
  postgresql: "9.6"
  chrome: stable
before_install:
  - "export STRONGMING_SPEC=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem update --system
  - gem install bundler

before_script:
  - psql -c 'create database myapp_test;' -U postgres;
  - RAILS_ENV=test bundle exec rake db:migrate
script:
  - STRONGMING_SPEC=1 bundle exec rspec spec_strongmind/models
gemfile:
  - Gemfile
cache: bundler