rvm:
  - 2.4.1
services:
  - redis-server
  - postgresql
addons:
  postgresql: "9.6"
  chrome: stable
cache: bundler
before_install:
  - sudo apt-get install -y libxmlsec1 libxmlsec1-dev imagemagick
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem uninstall bundler -x || gem uninstall bundler -a || true
  - gem update --system 2.6.12
  - which gem
  - gem --version
  - which bundle
  - bundler --version
  - gem uninstall bundler -x -i /home/travis/.rvm/gems/ruby-2.4.1@global || gem uninstall bundler -a -i /home/travis/.rvm/gems/ruby-2.4.1@global || true
  - gem install bundler --version=1.15.1
  - gem list bundler
  - which bundle
  - bundler --version
  - rvm info
  - nvm install v6.9
  - npm install -g coffee-script@1.6.2
  - npm install -g gulp
  - npm install -g webpack
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - STRONGMIND_SPEC=1 bundle install --verbose --without production --jobs=3 --retry=1
before_script:
  - psql -c 'create database canvas_test;' -U postgres;
  - STRONGMIND_SPEC=1 RAILS_ENV=test bundle exec rake db:migrate
script:
  - STRONGMING_SPEC=1 bundle exec rspec spec_strongmind/models
