rvm:
  - 2.4.1
services:
  - redis-server
  - postgresql
addons:
  postgresql: "9.6"
  chrome: stable
bundler_args: --without production development
cache: bundler
before_install:
  - "export STRONGMING_SPEC=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem list bundler
  - gem uninstall bundler
  - gem list bundler
  - gem install bundler -v '1.15.1'
before_script:
  - psql -c 'create database canvas_test;' -U postgres;
  - RAILS_ENV=test bin/rake db:migrate
script:
  - STRONGMING_SPEC=1 bin/rspec spec_strongmind/models
