rvm:
  - 2.4.1
services:
  - redis-server
  - postgresql
addons:
  postgresql: "9.6"
  chrome: stable
cache: bundler
before_install:
  - sudo apt-get install -y libxmlsec1 libxmlsec1-dev imagemagick
  - gem install bundler --version=1.15.1
  - nvm install v6.9
  - npm install -g coffee-script@1.6.2
  - npm install -g gulp
  - npm install -g webpack
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - STRONGMIND_SPEC=1 bundle _1.15.1_ install --verbose --without production --jobs=3 --retry=1
before_script:
  - psql -c 'create database canvas_test;' -U postgres;
  - RAILS_ENV=test bin/rake db:migrate
script:
  - STRONGMING_SPEC=1 bin/rspec spec_strongmind/models
