config:
  aws:region: us-west-2
  isucceed:assume_role_policy:
    Statement:
    - Action: sts:AssumeRole
      Effect: Allow
      Principal:
        Service: ecs-tasks.amazonaws.com
      Sid: ""
    Version: "2012-10-17"
  isucceed:role_policy:
    Statement:
    - Action:
      - ecr:GetAuthorizationToken
      - ecr:BatchCheckLayerAvailability
      - ecr:GetDownloadUrlForLayer
      - ecr:BatchGetImage
      - ecr:GetRepositoryPolicy
      - ecr:DescribeRepositories
      - ecr:ListImages
      - ecr:DescribeImages
      - ecr:InitiateLayerUpload
      - ecr:UploadLayerPart
      - ecr:CompleteLayerUpload
      - ecr:PutImage
      - logs:CreateLogStream
      - logs:PutLogEvents
      Effect: Allow
      Resource: '*'
    Version: "2012-10-17"
  isucceed:tags:
    environment: stage
    owner: devops
    product: canvas-lms
    service: canvas-lms
  isucceed:ecs:
  - cpu: "256"
    entryPoint:
    - sh
    - -c
    - /usr/src/run.sh
    image: 448312246740.dkr.ecr.us-west-2.amazonaws.com/canvas-web
    memory: "512"
    name: web
    port_mapping:
    - containerPort: 3000
      hostPort: 3000
  - cpu: "256"
    entryPoint:
    - sh
    - -c
    - /usr/src/worker.sh
    image: 448312246740.dkr.ecr.us-west-2.amazonaws.com/canvas-worker
    memory: "512"
    name: worker
    port_mapping:
    - containerPort: 3000
      hostPort: 3000